In [1]:
# Tecnología
import json
import calendar
import pandas as pd
from sparky_bc import Sparky
import datetime as dt
from dateutil.relativedelta import relativedelta

# files lz conection
path_sparky_conf = '/Users/santlond/Documents/sparky_conf.json'

# Configurar conexión a LZ
with open(path_sparky_conf, 'rb') as JSON_lz_File:
    sp_config = json.loads(JSON_lz_File.read())
    
USER='santlond'
PASS=sp_config['ID']
DSN='IMPALA_PROD'
LOGDIR= 'logs'
sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp")
# sparky = Sparky(username=USER, password=PASS, dsn=DSN)

helper = sparky.helper

2025-09-30 16:45:42 - [WARNING] - No se encontro la carpeta "/Users/santlond/Documents/ADQUIRENCIA_FERIA_EVA/logs" para guardar los logs

 ____  _____ __  __  ___ _____ _____
|  _ \| ____|  \/  |/ _ \_   _| ____|
| |_) |  _| | |\/| | | | || | |  _|
|  _ <| |___| |  | | |_| || | | |___
|_| \_\_____|_|  |_|\___/ |_| |_____|

 ____  ____   _    ____  _  __
/ ___||  _ \ / \  |  _ \| |/ /
\___ \| |_) / _ \ | |_) | ' /
 ___) |  __/ ___ \|  _ <| . \
|____/|_| /_/   \_\_| \_\_|\_\

# Vinculaciones adquirencia

La tabla para obtener a lo largo del tiempo los comercios con adquirencia es tan pequeña que no es necesario crear un script que primero generé un histórico y luego un script que actualice ese histórico. Por tanto, cada vez que se necesite la evolución del kpi, se creará desde la tabla fuente:

`resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf`

In [10]:
dict_ult_ing_vinculacion = helper.obtener_ultima_ingestion('resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf')
dict_ult_ing_vinculacion

2025-10-01 08:42:39 - [INFO] - Buscando fechas para resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf
/Users/santlond/anaconda3/envs/env_odbc_py39/lib/python3.9/site-packages/helper/helper.py:421: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
2025-10-01 08:42:40 - [WARNING] - Error en la busqueda de ultima ingestion para la tabla resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf, intentando nuevamente
2025-10-01 08:42:40 - [INFO] - Finalizo la busqueda, duracion: 00:01.1, resultado: {'year': 2025, 'month': 9, 'day': 26}

{'year': 2025, 'month': 9, 'day': 26}

In [93]:
# Ingestión información de vinculación
# Se debe esperar hasta el siguiente mes para obtener la vinculación del mes actual
sql = """
SELECT ingestion_year, ingestion_month, ingestion_day, year, month, day, periodo, count(*) as frec
FROM resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf
WHERE YEAR BETWEEN 2024 and 2025
  AND MONTH  BETWEEN 1 and 12
  AND DAY BETWEEN 1 and 31
GROUP BY 1,2,3,4,5,6,7
ORDER BY periodo desc, year DESC, month desc, day desc, ingestion_year desc, ingestion_month desc, ingestion_day desc;
"""
helper.obtener_dataframe(sql).head(20)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 42/42 DATAFRAME                                            ejecutando   11:26:21 AM

2025-10-01 11:26:32 - [INFO] - 27 filas, 8 columnas, 00:10.9 consultando, 00:00.1 descargando, 00:00.0 convirtiendo

 42/42 DATAFRAME                                            finalizado   11:26:21 AM     00:11.0
-------------------------------------------------------------------------------------------------

,ingestion_year,ingestion_month,ingestion_day,year,month,day,periodo,frec
0,2025,9,26,2025,9,26,202509.0,1638
1,2025,9,26,2025,9,26,202508.0,4225
2,2025,8,8,2025,8,8,202507.0,3817
3,2025,7,8,2025,7,8,202506.0,3092
4,2025,6,18,2025,6,18,202505.0,3198
5,2025,5,6,2025,5,6,202504.0,3244
6,2025,4,4,2025,4,4,202503.0,2827
7,2025,3,11,2025,3,11,202502.0,2735
8,2025,2,7,2025,2,7,202501.0,2361
9,2025,1,11,2025,1,11,202412.0,3325
10,2024,12,5,2024,12,5,202411.0,3059
11,2024,11,13,2024,11,13,202410.0,3233
12,2024,10,11,2024,10,11,202409.0,4040
13,2024,9,9,2024,9,9,202408.0,3248
14,2024,8,22,2024,8,22,202407.0,4428
15,2024,8,12,2024,7,8,202406.0,1722
16,2024,6,21,2024,6,21,202406.0,1194
17,2024,6,13,2024,6,13,202405.0,1852
18,2024,5,24,2024,5,24,202405.0,1468
19,2024,5,7,2024,5,7,202404.0,1547

In [91]:
# Número de Vinculaciones
sql = """
WITH vinc AS
  (SELECT periodo,
          count(*) AS num_vinc,
          cast(left(cast(periodo AS STRING), 4) AS int) AS YEAR,
          cast(right(cast(periodo AS STRING), 2) AS int) AS mes
   FROM resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf
   WHERE YEAR BETWEEN 2020 AND 2025
     AND MONTH BETWEEN 1 AND 12
     AND DAY BETWEEN 1 AND 31
     AND periodo IS NOT NULL
   GROUP BY 1
   ORDER BY periodo DESC)
SELECT periodo,
       num_vinc,
       sum(num_vinc) OVER (PARTITION BY YEAR
                           ORDER BY YEAR,
                                    mes ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_vinc_cumsum_year_mes
FROM vinc
ORDER BY periodo DESC;
"""
helper.obtener_dataframe(sql).head(20)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 40/40 DATAFRAME                                             falló n.1   11:03:36 AM
 40/40 DATAFRAME                                             intento 2   11:03:36 AM

2025-10-01 11:04:29 - [INFO] - 69 filas, 5 columnas, 00:52.5 consultando, 00:00.1 descargando, 00:00.0 convirtiendo

 40/40 DATAFRAME                                            finalizado   11:03:36 AM     00:52.7
-------------------------------------------------------------------------------------------------

     periodo  year  mes  num_vinc  num_vinc_cumsum_year_mes
0   202509.0  2025    9      1638                     27137
1   202508.0  2025    8      4225                     25499
2   202507.0  2025    7      3817                     21274
3   202506.0  2025    6      3092                     17457
4   202505.0  2025    5      3198                     14365
5   202504.0  2025    4      3244                     11167
6   202503.0  2025    3      2827                      7923
7   202502.0  2025    2      2735                      5096
8   202501.0  2025    1      2361                      2361
9   202412.0  2024   12      3325                     41666
10  202411.0  2024   11      3059                     38341
11  202410.0  2024   10      3233                     35282
12  202409.0  2024    9      4040                     32049
13  202408.0  2024    8      3248                     28009
14  202407.0  2024    7      4428                     24761
15  202406.0  2024    6      2916                     20333
16  202405.0  2024    5      3320                     17417
17  202404.0  2024    4      3340                     14097
18  202403.0  2024    3      3440                     10757
19  202402.0  2024    2      4191                      7317

# Uso adquirencia o activo en adquirencia

Un comercio usa adquirencia en un mes específico o mes de análisis cuando:

- Métrica Normal: tienen al menos 1 trx aporbada en ese mes.

- Métrica 5x: tiene al menos 1 trx aprobada en los últimos seis meses, incluyendo el mes de análisis

## Análisis ingestión compras tabla transaccional adquirencia

In [95]:
# Se deben esperar dos días para que se ingeste la información completa de las transacciones de un día en particular
# Para obtener la información de las compras del día jueves y viernes se debe espear hasta la sgte semana
sql = """
WITH outcome1 AS
  (SELECT YEAR,
          MONTH,
          DAY,
          left(cast(f_trx as string), 10) as f_trx,
          count(*) AS num_compras
   FROM resultados_vspc_medios_de_pago.gsap_m_transaccional
   WHERE YEAR IN (2025)
     AND MONTH BETWEEN 8 AND 9
     AND DAY BETWEEN 1 AND 31
     and tipo_trx = "Purchase"
   GROUP BY 1,
            2,
            3,
            4
   ORDER BY f_trx DESC, YEAR DESC, MONTH DESC, DAY DESC),
     outcome2 AS
  (SELECT *,
          sum(num_compras) OVER (PARTITION BY f_trx) AS total_compras,
                                sum(num_compras) OVER (PARTITION BY f_trx
                                                       ORDER BY YEAR,
                                                                MONTH,
                                                                DAY ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_compras_cumsum
   FROM outcome1
   ORDER BY f_trx DESC, YEAR DESC, MONTH DESC, DAY DESC)
SELECT *,
       row_number() OVER (PARTITION BY f_trx
                          ORDER BY YEAR,
                                   MONTH,
                                   DAY) AS num_ing,
                         round(num_compras /total_compras, 4) AS prop,
                         round(num_compras_cumsum / total_compras, 4) AS prop_cumsum
FROM outcome2
ORDER BY f_trx DESC,
         YEAR DESC, MONTH DESC, DAY DESC;
"""
helper.obtener_dataframe(sql)[0:20]

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 44/44 DATAFRAME                                            ejecutando   11:29:37 AM

2025-10-01 11:29:54 - [INFO] - 1,510 filas, 10 columnas, 00:16.6 consultando, 00:00.1 descargando, 00:00.0 convirtiendo

 44/44 DATAFRAME                                            finalizado   11:29:37 AM     00:16.8
-------------------------------------------------------------------------------------------------

,year,month,day,f_trx,num_compras,total_compras,num_compras_cumsum,num_ing,prop,prop_cumsum
0,2025,9,11,2025-10-01,1,1,1,1,1.0000,1.0000
1,2025,9,29,2025-09-29,34,34,34,1,1.0000,1.0000
2,2025,9,29,2025-09-28,1890063,1890063,1890063,1,1.0000,1.0000
3,2025,9,29,2025-09-27,2301178,2301178,2301178,1,1.0000,1.0000
4,2025,9,29,2025-09-26,2001121,2001177,2001177,2,1.0000,1.0000
5,2025,9,26,2025-09-26,56,2001177,56,1,0.0000,0.0000
6,2025,9,29,2025-09-25,51417,1783604,1783604,3,0.0288,1.0000
7,2025,9,26,2025-09-25,1732143,1783604,1732187,2,0.9711,0.9712
8,2025,9,25,2025-09-25,44,1783604,44,1,0.0000,0.0000
9,2025,9,29,2025-09-24,112,1653032,1653032,4,0.0001,1.0000
10,2025,9,26,2025-09-24,41919,1653032,1652920,3,0.0254,0.9999
11,2025,9,25,2025-09-24,1610956,1653032,1611001,2,0.9745,0.9746
12,2025,9,24,2025-09-24,45,1653032,45,1,0.0000,0.0000
13,2025,9,29,2025-09-23,5,1612143,1612143,5,0.0000,1.0000
14,2025,9,26,2025-09-23,80,1612143,1612138,4,0.0000,1.0000
15,2025,9,25,2025-09-23,38138,1612143,1612058,3,0.0237,0.9999
16,2025,9,24,2025-09-23,1573877,1612143,1573920,2,0.9763,0.9763
17,2025,9,23,2025-09-23,43,1612143,43,1,0.0000,0.0000
18,2025,9,29,2025-09-22,5,1568805,1568805,5,0.0000,1.0000
19,2025,9,25,2025-09-22,60,1568805,1568800,4,0.0000,1.0000

## Construcción histórico transacciones

In [ ]:
# Construcción histórico trxs
# Se selecciona el rango de tiempo de las transacciones a extraer
fecha_inicial = '2022-09-01' # MODIFICAR.
fecha_final = '2025-09-05' # MODIFICAR.
fecha_inicial_ts = pd.to_datetime(fecha_inicial)
fecha_final_ts = pd.to_datetime(fecha_final)
fechas = pd.date_range(start=fecha_inicial, end=fecha_final, freq='D')

# Ir por las particiones del siguiente mes que contendrá las compras de los últimos días del reango de tiempo deseado
pri_dia_part = fechas[-1] + relativedelta(days=1)
pri_dia_part = pri_dia_part.date().isoformat() # Primer día de partición para buscar compras del primer día.
ult_dia_part = fechas[-1] + relativedelta(days=10)
ult_dia_part = ult_dia_part.date().isoformat()
fechas_faltantes = pd.date_range(start=pri_dia_part, end=ult_dia_part, freq='D')

# siguiente_dias = dt.datetime(siguientes_dias.year, siguientes_dias.month, calendar.monthrange(siguientes_dias.year, siguientes_dias.month)[1])
fechas = fechas.append(fechas_faltantes)

# df_config
df_config = pd.DataFrame({'fechas': fechas})
df_config['year'] = df_config['fechas'].dt.year
df_config['month'] = df_config['fechas'].dt.month
df_config['day'] = df_config['fechas'].dt.day
df_config

        fechas  year  month  day
0   2022-09-01  2022      9    1
1   2022-09-02  2022      9    2
2   2022-09-03  2022      9    3
3   2022-09-04  2022      9    4
4   2022-09-05  2022      9    5
..         ...   ...    ...  ...
117 2022-12-27  2022     12   27
118 2022-12-28  2022     12   28
119 2022-12-29  2022     12   29
120 2022-12-30  2022     12   30
121 2022-12-31  2022     12   31

[122 rows x 4 columns]

In [ ]:
# # Crear tabla que almacenará la información

# sql = """
# CREATE TABLE proceso_bluekai.mdo_adquirencia_trxs  (
#                 cod_unico VARCHAR,
#                 f_trx TIMESTAMP,
#                 num_trxs BIGINT,
#                 mnt_total_trxs DECIMAL(38,2)
#                 )
#             PARTITIONED BY 
#             (
#             YEAR INT,
#             MES INT,
#             DIA INT
#             )
# STORED AS PARQUET
# TBLPROPERTIES ('transactional' = 'false');
# """
# helper.ejecutar_consulta(sql)

# sql_compute = """COMPUTE STATS proceso_bluekai.mdo_adquirencia_trxs;"""

---------------------------------------------------------------------------------------------
   i     tipo                   nombre                   estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------
 53/53      DROP proceso_bluekai.mdo_adquirencia_trxs   finalizado   07:47:50 AM     00:01.2
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
   i     tipo                   nombre                   estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------
 54/54    CREATE proceso_bluekai.mdo_adquirencia_trxs   finalizado   07:47:51 AM     00:00.1
---------------------------------------------------------------------------------------------

In [37]:
# Iterar para obtener las trxs por cliente
for row in df_config.itertuples():
    print('#' * 50)
    print('')
    print('Exrayendo datos de las particiones: ', str(row.year), '-', str(row.month), '-', str(row.day))
    print('')
    print('Obteniendo transacciones adquirencia de los comercios')
    print('')

    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_trxs_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)

    sql = """
    CREATE TABLE proceso.mdo_adquirencia_trxs_temp STORED AS PARQUET AS
    SELECT cod_unico,
       f_trx,
       count(*) AS num_trxs,
       sum(mnt_total_trx) AS mnt_total_trxs,
        """ + str(row.year) + """ AS YEAR,
        """ + str(row.month) + """ AS MES,
        """ + str(row.day) + """ AS DIA
    FROM resultados_vspc_medios_de_pago.gsap_m_transaccional
    WHERE YEAR = """ + str(row.year) + """
     AND MONTH = """ + str(row.month) + """
     AND DAY = """ + str(row.day) + """
     AND tipo_trx = "Purchase"
    GROUP BY 1,
            2;"""
    helper.ejecutar_consulta(sql)

    sql_compute = """COMPUTE STATS proceso.mdo_adquirencia_trxs_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Insertando transacciones adquirencia de los comercios')
    print('')

    sql = """
    INSERT INTO proceso_bluekai.mdo_adquirencia_trxs PARTITION (YEAR, MES, DIA)
    SELECT cod_unico,
           f_trx,
           num_trxs,
           mnt_total_trxs,
           YEAR,
           MES,
           DIA
    FROM proceso.mdo_adquirencia_trxs_temp;"""
    helper.ejecutar_consulta(sql)
    print('')

##################################################

Exrayendo datos de las particiones:  2022 - 9 - 1

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3981/3981      DROP    proceso.mdo_adquirencia_trxs_temp    falló n.1   11:52:35 AM
 3981/3981      DROP    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:35 AM     00:01.7
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3982/3982    CREATE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:37 AM     00:01.6
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3983/3983   COMPUTE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:38 AM     00:00.7
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3984/3984    INSERT proceso_bluekai.mdo_adquirencia_trxs   finalizado   11:52:39 AM     00:01.2
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 9 - 2

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3985/3985      DROP    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:40 AM     00:00.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3986/3986    CREATE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:41 AM     00:01.7
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3987/3987   COMPUTE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:43 AM     00:00.8
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3988/3988    INSERT proceso_bluekai.mdo_adquirencia_trxs   finalizado   11:52:44 AM     00:01.2
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 9 - 3

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3989/3989      DROP    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:45 AM     00:00.6
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3990/3990    CREATE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:45 AM     00:00.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3991/3991   COMPUTE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:46 AM     00:00.6
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3992/3992    INSERT proceso_bluekai.mdo_adquirencia_trxs   finalizado   11:52:47 AM     00:00.3
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 9 - 4

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3993/3993      DROP    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:47 AM     00:00.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3994/3994    CREATE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:48 AM     00:00.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3995/3995   COMPUTE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:48 AM     00:00.7
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3996/3996    INSERT proceso_bluekai.mdo_adquirencia_trxs   finalizado   11:52:49 AM     00:00.4
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 9 - 5

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3997/3997      DROP    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:49 AM     00:00.3
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3998/3998    CREATE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:50 AM     00:02.1
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 3999/3999   COMPUTE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:52 AM     00:01.1
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4000/4000    INSERT proceso_bluekai.mdo_adquirencia_trxs   finalizado   11:52:53 AM     00:01.3
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 9 - 6

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4001/4001      DROP    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:55 AM     00:00.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4002/4002    CREATE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:55 AM     00:01.1
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4003/4003   COMPUTE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:56 AM     00:00.7
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4004/4004    INSERT proceso_bluekai.mdo_adquirencia_trxs   finalizado   11:52:57 AM     00:01.0
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 9 - 7

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4005/4005      DROP    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:58 AM     00:00.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4006/4006    CREATE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:52:59 AM     00:01.3
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4007/4007   COMPUTE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:53:00 AM     00:03.8
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4008/4008    INSERT proceso_bluekai.mdo_adquirencia_trxs   finalizado   11:53:04 AM     00:01.1
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 9 - 8

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4009/4009      DROP    proceso.mdo_adquirencia_trxs_temp   finalizado   11:53:05 AM     00:00.3
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4010/4010    CREATE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:53:05 AM     00:01.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4011/4011   COMPUTE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:53:07 AM     00:00.8
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4012/4012    INSERT proceso_bluekai.mdo_adquirencia_trxs   finalizado   11:53:08 AM     00:01.1
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 9 - 9

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4013/4013      DROP    proceso.mdo_adquirencia_trxs_temp   finalizado   11:53:09 AM     00:00.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4014/4014    CREATE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:53:09 AM     00:01.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4015/4015   COMPUTE    proceso.mdo_adquirencia_trxs_temp   finalizado   11:53:11 AM     00:00.8
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 4016/4016    INSERT proceso_bluekai.mdo_adquirencia_trxs   finalizado   11:53:12 AM     00:01.3
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 9 - 10

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
     i       tipo                   nombre                   estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------

In [8]:
# Verificar cantidad de registros por partición
# La última ingestión usada 2025-05-05 para obtener las transacciones.
sql = """
SELECT YEAR,
       mes,
       dia,
       left(cast(f_trx AS string), 10),
       count(*) AS frec
FROM proceso_bluekai.mdo_adquirencia_trxs
WHERE YEAR BETWEEN 2022 AND 2025
  AND mes BETWEEN 1 AND 12
  AND dia BETWEEN 1 AND 31
GROUP BY 1,
         2,
         3,
         4
ORDER BY left(cast(f_trx AS string), 10) DESC, YEAR DESC, mes DESC,
                                                          dia DESC;
"""
helper.obtener_dataframe(sql).head(20)

------------------------------------------------------------
  i    tipo    nombre    estado     hora_inicio   duracion
------------------------------------------------------------
 6/6 DATAFRAME        descargando   04:56:40 PM

2025-09-30 16:56:44 - [INFO] - 27,679 filas, 5 columnas, 00:03.5 consultando, 00:00.7 descargando, 00:00.0 convirtiendo

 6/6 DATAFRAME         finalizado   04:56:40 PM     00:04.4
------------------------------------------------------------

    year  mes  dia      expr_1    frec
0   2025    8   26  2025-09-19       1
1   2025    8   26  2025-09-16       1
2   2025    9    5  2025-09-05       4
3   2025    9    5  2025-09-04  410078
4   2025    9    4  2025-09-04       3
5   2025    9    5  2025-09-03   16341
6   2025    9    4  2025-09-03  432313
7   2025    9    3  2025-09-03       4
8   2025    9    5  2025-09-02      94
9   2025    9    4  2025-09-02   15441
10  2025    9    3  2025-09-02  432678
11  2025    9    2  2025-09-02       4
12  2025    9    5  2025-09-01       5
13  2025    9    4  2025-09-01      73
14  2025    9    3  2025-09-01   14559
15  2025    9    2  2025-09-01  422288
16  2025    9    1  2025-09-01       4
17  2025    9    5  2025-08-31       1
18  2025    9    4  2025-08-31       3
19  2025    9    3  2025-08-31      76

## Construcción histórico transacciones por mes

In [114]:
# Crear tabla que almacenará las transacciones menusales por cliente
sql = """
CREATE TABLE proceso_bluekai.mdo_adquirencia_trxs_mes_1  (
                cod_unico VARCHAR,
                num_trxs BIGINT,
                mnt_total_trxs DECIMAL(38,2)
                )
            PARTITIONED BY 
            (
            periodo_trxs INT
            )
STORED AS PARQUET
TBLPROPERTIES ('transactional' = 'false');
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE STATS proceso_bluekai.mdo_adquirencia_trxs_mes_1;"""

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 47/47    CREATE ...so_bluekai.mdo_adquirencia_trxs_mes_1   finalizado   03:35:29 PM     00:00.5
-------------------------------------------------------------------------------------------------

In [116]:
# Construcción histórico trxs mes
# Se selecciona el rango de tiempo de las transacciones a extraer
fecha_inicial = '2022-01-01' # MODIFICAR.
fecha_final = '2025-09-30' # MODIFICAR.
fecha_inicial_ts = pd.to_datetime(fecha_inicial)
fecha_final_ts = pd.to_datetime(fecha_final)
fechas = pd.date_range(start=fecha_inicial, end=fecha_final, freq='MS')

# # Ir por las particiones del siguiente mes que contendrá las compras de los últimos días del reango de tiempo deseado
# pri_dia_part = fechas[-1] + relativedelta(days=1)
# pri_dia_part = pri_dia_part.date().isoformat() # Primer día de partición para buscar compras del primer día.
# ult_dia_part = fechas[-1] + relativedelta(days=10)
# ult_dia_part = ult_dia_part.date().isoformat()
# fechas_faltantes = pd.date_range(start=pri_dia_part, end=ult_dia_part, freq='D')

# # siguiente_dias = dt.datetime(siguientes_dias.year, siguientes_dias.month, calendar.monthrange(siguientes_dias.year, siguientes_dias.month)[1])
# fechas = fechas.append(fechas_faltantes)

# df_config
df_config = pd.DataFrame({'fechas': fechas})
df_config['year'] = df_config['fechas'].dt.year
df_config['month'] = df_config['fechas'].dt.month
df_config['day'] = df_config['fechas'].dt.day
df_config['fechas_fin_mes'] = df_config['fechas'].apply(lambda x: x + relativedelta(months=1) - relativedelta(days=1))
df_config['year_fin_mes'] = df_config['fechas_fin_mes'].dt.year
df_config['month_fin_mes'] = df_config['fechas_fin_mes'].dt.month
df_config['day_fin_mes'] = df_config['fechas_fin_mes'].dt.day
df_config

,fechas,year,month,day,fechas_fin_mes,year_fin_mes,month_fin_mes,day_fin_mes
0,2022-01-01,2022,1,1,2022-01-31,2022,1,31
1,2022-02-01,2022,2,1,2022-02-28,2022,2,28
2,2022-03-01,2022,3,1,2022-03-31,2022,3,31
3,2022-04-01,2022,4,1,2022-04-30,2022,4,30
4,2022-05-01,2022,5,1,2022-05-31,2022,5,31
5,2022-06-01,2022,6,1,2022-06-30,2022,6,30
6,2022-07-01,2022,7,1,2022-07-31,2022,7,31
7,2022-08-01,2022,8,1,2022-08-31,2022,8,31
8,2022-09-01,2022,9,1,2022-09-30,2022,9,30
9,2022-10-01,2022,10,1,2022-10-31,2022,10,31
10,2022-11-01,2022,11,1,2022-11-30,2022,11,30
11,2022-12-01,2022,12,1,2022-12-31,2022,12,31
12,2023-01-01,2023,1,1,2023-01-31,2023,1,31
13,2023-02-01,2023,2,1,2023-02-28,2023,2,28
14,2023-03-01,2023,3,1,2023-03-31,2023,3,31
15,2023-04-01,2023,4,1,2023-04-30,2023,4,30
16,2023-05-01,2023,5,1,2023-05-31,2023,5,31
17,2023-06-01,2023,6,1,2023-06-30,2023,6,30
18,2023-07-01,2023,7,1,2023-07-31,2023,7,31
19,2023-08-01,2023,8,1,2023-08-31,2023,8,31
20,2023-09-01,2023,9,1,2023-09-30,2023,9,30
21,2023-10-01,2023,10,1,2023-10-31,2023,10,31
22,2023-11-01,2023,11,1,2023-11-30,2023,11,30
23,2023-12-01,2023,12,1,2023-12-31,2023,12,31
24,2024-01-01,2024,1,1,2024-01-31,2024,1,31
25,2024-02-01,2024,2,1,2024-02-29,2024,2,29
26,2024-03-01,2024,3,1,2024-03-31,2024,3,31
27,2024-04-01,2024,4,1,2024-04-30,2024,4,30
28,2024-05-01,2024,5,1,2024-05-31,2024,5,31
29,2024-06-01,2024,6,1,2024-06-30,2024,6,30
30,2024-07-01,2024,7,1,2024-07-31,2024,7,31
31,2024-08-01,2024,8,1,2024-08-31,2024,8,31
32,2024-09-01,2024,9,1,2024-09-30,2024,9,30
33,2024-10-01,2024,10,1,2024-10-31,2024,10,31
34,2024-11-01,2024,11,1,2024-11-30,2024,11,30
35,2024-12-01,2024,12,1,2024-12-31,2024,12,31
36,2025-01-01,2025,1,1,2025-01-31,2025,1,31
37,2025-02-01,2025,2,1,2025-02-28,2025,2,28
38,2025-03-01,2025,3,1,2025-03-31,2025,3,31
39,2025-04-01,2025,4,1,2025-04-30,2025,4,30
40,2025-05-01,2025,5,1,2025-05-31,2025,5,31
41,2025-06-01,2025,6,1,2025-06-30,2025,6,30
42,2025-07-01,2025,7,1,2025-07-31,2025,7,31
43,2025-08-01,2025,8,1,2025-08-31,2025,8,31
44,2025-09-01,2025,9,1,2025-09-30,2025,9,30

In [120]:
for row in df_config.itertuples():
    print('#' * 50)
    print('')
    print('Exrayendo datos de las particiones: ', str(row.year), '-', str(row.month))
    print('')
    print('Obteniendo transacciones adquirencia de los comercios')
    print('')

    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_trxs_mes_1_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)

    sql = """
    CREATE TABLE proceso.mdo_adquirencia_trxs_mes_1_temp STORED AS PARQUET AS
    SELECT cod_unico,
           cast(replace(left(cast(f_trx AS string), 7), '-', '') AS INT) AS periodo_trxs,
           count(*) AS num_trxs,
           sum(mnt_total_trxs) AS mnt_total_trxs
    FROM proceso_bluekai.mdo_adquirencia_trxs
    WHERE YEAR = """ + str(row.year) + """
     AND MES = """ + str(row.month) + """
     AND DIA BETWEEN """ + str(row.day) + """ AND """ + str(row.day_fin_mes) + """
    GROUP BY 1,
             2;"""
    helper.ejecutar_consulta(sql)

    sql_compute = """COMPUTE STATS proceso.mdo_adquirencia_trxs_mes_1_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Insertando transacciones adquirencia de los comercios')
    print('')

    sql = """
    INSERT INTO proceso_bluekai.mdo_adquirencia_trxs_mes_1 PARTITION (periodo_trxs)
    SELECT cod_unico,
           num_trxs,
           mnt_total_trxs,
           periodo_trxs
    FROM proceso.mdo_adquirencia_trxs_mes_1_temp;"""
    helper.ejecutar_consulta(sql)
    print('')

##################################################

Exrayendo datos de las particiones:  2022 - 1

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 56/56      DROP  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:26 PM     00:00.5
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 57/57    CREATE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:27 PM     00:05.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 58/58   COMPUTE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:33 PM     00:03.2
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 59/59    INSERT ...so_bluekai.mdo_adquirencia_trxs_mes_1   finalizado   03:52:36 PM     00:01.4
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 2

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 60/60      DROP  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:37 PM     00:00.5
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 61/61    CREATE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:38 PM     00:01.7
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 62/62   COMPUTE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:40 PM     00:04.2
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 63/63    INSERT ...so_bluekai.mdo_adquirencia_trxs_mes_1   finalizado   03:52:44 PM     00:01.7
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 3

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 64/64      DROP  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:46 PM     00:00.6
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 65/65    CREATE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:46 PM     00:04.1
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 66/66   COMPUTE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:51 PM     00:02.6
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 67/67    INSERT ...so_bluekai.mdo_adquirencia_trxs_mes_1   finalizado   03:52:53 PM     00:01.3
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 4

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 68/68      DROP  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:55 PM     00:00.5
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 69/69    CREATE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:52:55 PM     00:05.9
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 70/70   COMPUTE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:01 PM     00:08.4
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 71/71    INSERT ...so_bluekai.mdo_adquirencia_trxs_mes_1   finalizado   03:53:10 PM     00:02.7
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 5

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 72/72      DROP  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:13 PM     00:00.5
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 73/73    CREATE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:13 PM     00:04.1
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 74/74   COMPUTE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:18 PM     00:08.2
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 75/75    INSERT ...so_bluekai.mdo_adquirencia_trxs_mes_1   finalizado   03:53:26 PM     00:03.7
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 6

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 76/76      DROP  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:30 PM     00:00.5
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 77/77    CREATE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:30 PM     00:01.8
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 78/78   COMPUTE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:32 PM     00:04.2
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 79/79    INSERT ...so_bluekai.mdo_adquirencia_trxs_mes_1   finalizado   03:53:37 PM     00:02.3
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 7

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 80/80      DROP  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:39 PM     00:00.5
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 81/81    CREATE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:40 PM     00:04.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 82/82   COMPUTE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:44 PM     00:04.8
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 83/83    INSERT ...so_bluekai.mdo_adquirencia_trxs_mes_1   finalizado   03:53:49 PM     00:04.1
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 8

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 84/84      DROP  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:53 PM     00:00.5
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 85/85    CREATE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:54 PM     00:04.0
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 86/86   COMPUTE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:53:58 PM     00:06.1
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 87/87    INSERT ...so_bluekai.mdo_adquirencia_trxs_mes_1   finalizado   03:54:04 PM     00:01.2
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 9

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 88/88      DROP  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:54:05 PM     00:00.8
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 89/89    CREATE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:54:06 PM     00:03.6
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 90/90   COMPUTE  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:54:10 PM     00:08.1
-------------------------------------------------------------------------------------------------

Insertando transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 91/91    INSERT ...so_bluekai.mdo_adquirencia_trxs_mes_1   finalizado   03:54:18 PM     00:03.8
-------------------------------------------------------------------------------------------------

##################################################

Exrayendo datos de las particiones:  2022 - 10

Obteniendo transacciones adquirencia de los comercios

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 92/92      DROP  proceso.mdo_adquirencia_trxs_mes_1_temp   finalizado   03:54:22 PM     00:00.5

## Construcción histórico métrica 5x

In [132]:
# Tabla que almacenará comercios con trxs por periodo
sql = """
CREATE TABLE proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist  (
                codigo_unico DOUBLE,
                periodo DOUBLE
                )
            PARTITIONED BY 
            (
            YEAR INT,
            MES INT
            )
STORED AS PARQUET
TBLPROPERTIES ('transactional' = 'false');
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE STATS proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist;"""
helper.ejecutar_consulta(sql_compute)

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 237/237    CREATE ...quirencia_vinculaciones_con_trxs_hist   finalizado   04:41:49 PM     00:00.5
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 238/238   COMPUTE ...quirencia_vinculaciones_con_trxs_hist   finalizado   04:41:50 PM     00:00.8
---------------------------------------------------------------------------------------------------

In [78]:
df_config.ult_6_meses_fin[0].replace(day=1)

Timestamp('2022-08-01 00:00:00')

In [124]:
# Construcción histórico trxs
# Se selecciona el rango de tiempo de las transacciones a extraer
fecha_inicial = '2023-01-01' # MODIFICAR.
fecha_final = '2025-08-31' # MODIFICAR.
fecha_inicial_ts = pd.to_datetime(fecha_inicial)
fecha_final_ts = pd.to_datetime(fecha_final)
fechas = pd.date_range(start=fecha_inicial, end=fecha_final, freq='M')

# # Ir por las particiones del siguiente mes que contendrá las compras de los últimos días del reango de tiempo deseado
# pri_dia_part = fechas[-1] + relativedelta(days=1)
# pri_dia_part = pri_dia_part.date().isoformat() # Primer día de partición para buscar compras del primer día.
# ult_dia_part = fechas[-1] + relativedelta(days=10)
# ult_dia_part = ult_dia_part.date().isoformat()
# fechas_faltantes = pd.date_range(start=pri_dia_part, end=ult_dia_part, freq='D')

# # siguiente_dias = dt.datetime(siguientes_dias.year, siguientes_dias.month, calendar.monthrange(siguientes_dias.year, siguientes_dias.month)[1])
# fechas = fechas.append(fechas_faltantes)

# df_config
df_config = pd.DataFrame({'fechas': fechas})
df_config['year'] = df_config['fechas'].dt.year
df_config['month'] = df_config['fechas'].dt.month
df_config['day'] = df_config['fechas'].dt.day
df_config['periodo'] = df_config['year'] * 100 + df_config['month']
df_config['periodo_base_year'] = df_config['year'] * 100 + 1
df_config['periodo_sgte_mes'] = df_config['fechas'].apply(lambda x: x + relativedelta(months=1))
df_config['year_sgte_mes'] = df_config['periodo_sgte_mes'].dt.year
df_config['periodo_sgte_mes'] = df_config['periodo_sgte_mes'].apply(lambda x: x.year * 100 + x.month)
df_config['ult_6_meses_fin'] = df_config['fechas'].apply(lambda x: x - relativedelta(months=5))
df_config['ult_6_meses_inicio'] = df_config['ult_6_meses_fin'].apply(lambda x: x.replace(day=1))
df_config['year_ult_6_meses'] = df_config['ult_6_meses_fin'].dt.year
df_config['month_ult_6_meses'] = df_config['ult_6_meses_fin'].dt.month
df_config['periodo_ult_6_meses'] = df_config['year_ult_6_meses'] * 100 + df_config['month_ult_6_meses']
df_config

,fechas,year,month,day,periodo,periodo_base_year,periodo_sgte_mes,year_sgte_mes,ult_6_meses_fin,ult_6_meses_inicio,year_ult_6_meses,month_ult_6_meses,periodo_ult_6_meses
0,2023-01-31,2023,1,31,202301,202301,202302,2023,2022-08-31,2022-08-01,2022,8,202208
1,2023-02-28,2023,2,28,202302,202301,202303,2023,2022-09-28,2022-09-01,2022,9,202209
2,2023-03-31,2023,3,31,202303,202301,202304,2023,2022-10-31,2022-10-01,2022,10,202210
3,2023-04-30,2023,4,30,202304,202301,202305,2023,2022-11-30,2022-11-01,2022,11,202211
4,2023-05-31,2023,5,31,202305,202301,202306,2023,2022-12-31,2022-12-01,2022,12,202212
5,2023-06-30,2023,6,30,202306,202301,202307,2023,2023-01-30,2023-01-01,2023,1,202301
6,2023-07-31,2023,7,31,202307,202301,202308,2023,2023-02-28,2023-02-01,2023,2,202302
7,2023-08-31,2023,8,31,202308,202301,202309,2023,2023-03-31,2023-03-01,2023,3,202303
8,2023-09-30,2023,9,30,202309,202301,202310,2023,2023-04-30,2023-04-01,2023,4,202304
9,2023-10-31,2023,10,31,202310,202301,202311,2023,2023-05-31,2023-05-01,2023,5,202305
10,2023-11-30,2023,11,30,202311,202301,202312,2023,2023-06-30,2023-06-01,2023,6,202306
11,2023-12-31,2023,12,31,202312,202301,202401,2024,2023-07-31,2023-07-01,2023,7,202307
12,2024-01-31,2024,1,31,202401,202401,202402,2024,2023-08-31,2023-08-01,2023,8,202308
13,2024-02-29,2024,2,29,202402,202401,202403,2024,2023-09-29,2023-09-01,2023,9,202309
14,2024-03-31,2024,3,31,202403,202401,202404,2024,2023-10-31,2023-10-01,2023,10,202310
15,2024-04-30,2024,4,30,202404,202401,202405,2024,2023-11-30,2023-11-01,2023,11,202311
16,2024-05-31,2024,5,31,202405,202401,202406,2024,2023-12-31,2023-12-01,2023,12,202312
17,2024-06-30,2024,6,30,202406,202401,202407,2024,2024-01-30,2024-01-01,2024,1,202401
18,2024-07-31,2024,7,31,202407,202401,202408,2024,2024-02-29,2024-02-01,2024,2,202402
19,2024-08-31,2024,8,31,202408,202401,202409,2024,2024-03-31,2024-03-01,2024,3,202403
20,2024-09-30,2024,9,30,202409,202401,202410,2024,2024-04-30,2024-04-01,2024,4,202404
21,2024-10-31,2024,10,31,202410,202401,202411,2024,2024-05-31,2024-05-01,2024,5,202405
22,2024-11-30,2024,11,30,202411,202401,202412,2024,2024-06-30,2024-06-01,2024,6,202406
23,2024-12-31,2024,12,31,202412,202401,202501,2025,2024-07-31,2024-07-01,2024,7,202407
24,2025-01-31,2025,1,31,202501,202501,202502,2025,2024-08-31,2024-08-01,2024,8,202408
25,2025-02-28,2025,2,28,202502,202501,202503,2025,2024-09-28,2024-09-01,2024,9,202409
26,2025-03-31,2025,3,31,202503,202501,202504,2025,2024-10-31,2024-10-01,2024,10,202410
27,2025-04-30,2025,4,30,202504,202501,202505,2025,2024-11-30,2024-11-01,2024,11,202411
28,2025-05-31,2025,5,31,202505,202501,202506,2025,2024-12-31,2024-12-01,2024,12,202412
29,2025-06-30,2025,6,30,202506,202501,202507,2025,2025-01-30,2025-01-01,2025,1,202501
30,2025-07-31,2025,7,31,202507,202501,202508,2025,2025-02-28,2025-02-01,2025,2,202502
31,2025-08-31,2025,8,31,202508,202501,202509,2025,2025-03-31,2025-03-01,2025,3,202503

In [134]:
for row in df_config.itertuples():
    print('#' * 50)
    print('')
    print('Obteniendo Métrica 5X')
    print('')
    print('Mes de Análisis: ', str(row.year), '-', str(row.month))
    print('')
    print('Obteniendo vinculaciones del año correspondiente acumuladas hasta el Mes de análisis')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_vinculaciones_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_vinculaciones_temp STORED AS PARQUET AS
    SELECT codigo_unico, """ + str(row.periodo) + """ AS periodo
    FROM resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf
    WHERE YEAR BETWEEN """ + str(row.year) + """ AND """ + str(row.year_sgte_mes) + """
    AND MONTH BETWEEN 1 AND 12
    AND DAY BETWEEN 1 AND 31
    AND periodo BETWEEN """ + str(row.periodo_base_year) + """ AND """ + str(row.periodo) + """ ;
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE STATS proceso.mdo_adquirencia_vinculaciones_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Obtener las transacciones seis meses hacia atrás')
    print('')
    sql_drop = """DROP TABLE IF EXISTS proceso.mdo_adquirencia_trxs_temp PURGE;"""
    helper.ejecutar_consulta(sql_drop)
    sql = """
    CREATE TABLE proceso.mdo_adquirencia_trxs_temp STORED AS PARQUET AS
    select distinct cod_unico
    FROM proceso_bluekai.mdo_adquirencia_trxs_mes_1
    WHERE periodo_trxs BETWEEN """ + str(row.periodo_ult_6_meses) + """ AND """ + str(row.periodo) + """;
    """
    helper.ejecutar_consulta(sql)
    sql_compute = """COMPUTE STATS proceso.mdo_adquirencia_trxs_temp;"""
    helper.ejecutar_consulta(sql_compute)

    print('')
    print('Insertando en tabla proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist')
    print('')
    
    sql = """
    INSERT INTO proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist PARTITION (YEAR,
                                                                                       MES)
    SELECT a.codigo_unico,
           a.periodo,
           """ + str(row.year) + """ AS YEAR,
           """ + str(row.month) + """ AS MES
    FROM proceso.mdo_adquirencia_vinculaciones_temp AS a
    INNER JOIN proceso.mdo_adquirencia_trxs_temp AS b ON CAST(a.codigo_unico AS BIGINT) = CAST(b.cod_unico AS BIGINT);
    """
    helper.ejecutar_consulta(sql)
    print('')

##################################################

Obteniendo Métrica 5X

Mes de Análisis:  2023 - 1

Obteniendo vinculaciones del año correspondiente acumuladas hasta el Mes de análisis

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 241/241      DROP ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:44:33 PM     00:00.4
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 242/242    CREATE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:44:34 PM     00:00.8
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 243/243   COMPUTE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:44:35 PM     00:01.3
---------------------------------------------------------------------------------------------------

Obtener las transacciones seis meses hacia atrás

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 244/244      DROP        proceso.mdo_adquirencia_trxs_temp   finalizado   04:44:36 PM     00:00.5
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 245/245    CREATE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:44:37 PM     00:05.2
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 246/246   COMPUTE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:44:42 PM     00:02.4
---------------------------------------------------------------------------------------------------

Insertando en tabla proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 247/247    INSERT ...quirencia_vinculaciones_con_trxs_hist   finalizado   04:44:45 PM     00:01.7
---------------------------------------------------------------------------------------------------

##################################################

Obteniendo Métrica 5X

Mes de Análisis:  2023 - 2

Obteniendo vinculaciones del año correspondiente acumuladas hasta el Mes de análisis

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 248/248      DROP ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:44:46 PM     00:00.5
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 249/249    CREATE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:44:47 PM     00:01.5
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 250/250   COMPUTE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:44:49 PM     00:03.3
---------------------------------------------------------------------------------------------------

Obtener las transacciones seis meses hacia atrás

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 251/251      DROP        proceso.mdo_adquirencia_trxs_temp   finalizado   04:44:52 PM     00:00.4
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 252/252    CREATE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:44:53 PM     00:04.3
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 253/253   COMPUTE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:44:57 PM     00:04.5
---------------------------------------------------------------------------------------------------

Insertando en tabla proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 254/254    INSERT ...quirencia_vinculaciones_con_trxs_hist   finalizado   04:45:02 PM     00:09.2
---------------------------------------------------------------------------------------------------

##################################################

Obteniendo Métrica 5X

Mes de Análisis:  2023 - 3

Obteniendo vinculaciones del año correspondiente acumuladas hasta el Mes de análisis

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 255/255      DROP ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:45:11 PM     00:00.7
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 256/256    CREATE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:45:12 PM     00:01.8
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 257/257   COMPUTE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:45:14 PM     00:00.8
---------------------------------------------------------------------------------------------------

Obtener las transacciones seis meses hacia atrás

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 258/258      DROP        proceso.mdo_adquirencia_trxs_temp   finalizado   04:45:15 PM     00:00.6
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 259/259    CREATE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:45:15 PM     00:06.9
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 260/260   COMPUTE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:45:22 PM     00:01.2
---------------------------------------------------------------------------------------------------

Insertando en tabla proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 261/261    INSERT ...quirencia_vinculaciones_con_trxs_hist   finalizado   04:45:24 PM     00:02.2
---------------------------------------------------------------------------------------------------

##################################################

Obteniendo Métrica 5X

Mes de Análisis:  2023 - 4

Obteniendo vinculaciones del año correspondiente acumuladas hasta el Mes de análisis

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 262/262      DROP ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:45:26 PM     00:00.6
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 263/263    CREATE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:45:26 PM     00:01.2
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 264/264   COMPUTE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:45:28 PM     00:00.7
---------------------------------------------------------------------------------------------------

Obtener las transacciones seis meses hacia atrás

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 265/265      DROP        proceso.mdo_adquirencia_trxs_temp   finalizado   04:45:29 PM     00:00.4
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 266/266    CREATE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:45:29 PM     00:03.8
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 267/267   COMPUTE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:45:33 PM     00:01.9
---------------------------------------------------------------------------------------------------

Insertando en tabla proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 268/268    INSERT ...quirencia_vinculaciones_con_trxs_hist   finalizado   04:45:35 PM     00:02.1
---------------------------------------------------------------------------------------------------

##################################################

Obteniendo Métrica 5X

Mes de Análisis:  2023 - 5

Obteniendo vinculaciones del año correspondiente acumuladas hasta el Mes de análisis

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 269/269      DROP ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:45:37 PM     00:00.4
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 270/270    CREATE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:45:38 PM     00:01.1
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 271/271   COMPUTE ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:45:39 PM     00:00.9
---------------------------------------------------------------------------------------------------

Obtener las transacciones seis meses hacia atrás

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 272/272      DROP        proceso.mdo_adquirencia_trxs_temp   finalizado   04:45:40 PM     00:00.5
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 273/273    CREATE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:45:41 PM     00:05.1
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 274/274   COMPUTE        proceso.mdo_adquirencia_trxs_temp   finalizado   04:45:46 PM     00:02.1
---------------------------------------------------------------------------------------------------

Insertando en tabla proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 275/275    INSERT ...quirencia_vinculaciones_con_trxs_hist   finalizado   04:45:48 PM     00:02.8
---------------------------------------------------------------------------------------------------

##################################################

Obteniendo Métrica 5X

Mes de Análisis:  2023 - 6

Obteniendo vinculaciones del año correspondiente acumuladas hasta el Mes de análisis

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 276/276      DROP ...so.mdo_adquirencia_vinculaciones_temp   finalizado   04:45:51 PM     00:00.5
---------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------

In [139]:
# Obtener uso por mes
# Número de Vinculaciones
sql = """
SELECT periodo,
       count(*) AS num_vinc_usando_5x
FROM proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist
WHERE YEAR BETWEEN 2020 AND 2025
  AND MES BETWEEN 1 AND 12
  AND periodo IS NOT NULL
GROUP BY 1
ORDER BY periodo DESC;
"""
helper.obtener_dataframe(sql).head(50)

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 469/469 DATAFRAME                                           descargando   05:03:44 PM

2025-10-01 17:03:50 - [INFO] - 32 filas, 5 columnas, 00:05.4 consultando, 00:00.3 descargando, 00:00.0 convirtiendo

 469/469 DATAFRAME                                            finalizado   05:03:44 PM     00:05.9
---------------------------------------------------------------------------------------------------

,periodo,year,mes,num_vinc_usando_5x,num_vinc_usando_5x_cumsum_year_mes
0,202508.0,2025,8,17701,72067
1,202507.0,2025,7,14880,54366
2,202506.0,2025,6,12224,39486
3,202505.0,2025,5,9981,27262
4,202504.0,2025,4,7578,17281
5,202503.0,2025,3,5211,9703
6,202502.0,2025,2,3192,4492
7,202501.0,2025,1,1300,1300
8,202412.0,2024,12,28017,191827
9,202411.0,2024,11,25704,163810
10,202410.0,2024,10,24003,138106
11,202409.0,2024,9,22105,114103
12,202408.0,2024,8,19602,91998
13,202407.0,2024,7,17765,72396
14,202406.0,2024,6,15140,54631
15,202405.0,2024,5,13073,39491
16,202404.0,2024,4,10688,26418
17,202403.0,2024,3,8351,15730
18,202402.0,2024,2,5303,7379
19,202401.0,2024,1,2076,2076
20,202312.0,2023,12,36895,242482
21,202311.0,2023,11,34154,205587
22,202310.0,2023,10,31363,171433
23,202309.0,2023,9,28762,140070
24,202308.0,2023,8,25903,111308
25,202307.0,2023,7,22813,85405
26,202306.0,2023,6,19308,62592
27,202305.0,2023,5,15462,43284
28,202304.0,2023,4,11850,27822
29,202303.0,2023,3,8794,15972
30,202302.0,2023,2,5127,7178
31,202301.0,2023,1,2051,2051

# Resultados

In [141]:
sql = """
WITH vinc AS
  (SELECT periodo,
          count(*) AS num_vinc,
          cast(left(cast(periodo AS STRING), 4) AS int) AS YEAR,
          cast(right(cast(periodo AS STRING), 2) AS int) AS mes
   FROM resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf
   WHERE YEAR BETWEEN 2020 AND 2025
     AND MONTH BETWEEN 1 AND 12
     AND DAY BETWEEN 1 AND 31
     AND periodo IS NOT NULL
   GROUP BY 1),
     vinc_acum AS
  (SELECT periodo,
          num_vinc,
          sum(num_vinc) OVER (PARTITION BY YEAR
                              ORDER BY YEAR,
                                       mes ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_vinc_cumsum_year_mes
   FROM vinc),
     vinc_uso AS
  (SELECT periodo,
          count(*) AS num_vinc_usando_5x
   FROM proceso_bluekai.mdo_adquirencia_vinculaciones_con_trxs_hist
   WHERE YEAR BETWEEN 2020 AND 2025
     AND MES BETWEEN 1 AND 12
     AND periodo IS NOT NULL
   GROUP BY 1),
     outcome1 AS
  (SELECT a.periodo,
          a.num_vinc,
          a.num_vinc_cumsum_year_mes,
          b.num_vinc_usando_5x
   FROM vinc_acum AS a
   LEFT JOIN vinc_uso AS b ON cast(a.periodo AS int) = cast(b.periodo AS int)
   WHERE a.periodo <= 202508)
SELECT a.periodo,
       a.num_vinc,
       a.num_vinc_cumsum_year_mes,
       a.num_vinc_usando_5x,
       round(a.num_vinc_usando_5x/a.num_vinc_cumsum_year_mes, 4) AS prop_uso
FROM outcome1 AS a
ORDER BY a.periodo DESC;
"""
helper.obtener_dataframe(sql).to_excel('main_data/evolucion_vinculaciones_y_metrica5x.xlsx', index=False)

---------------------------------------------------------------------------------------------------
    i      tipo                     nombre                     estado     hora_inicio   duracion
---------------------------------------------------------------------------------------------------
 471/471 DATAFRAME                                             falló n.1   09:51:58 AM
 471/471 DATAFRAME                                           descargando   09:51:58 AM

2025-10-03 09:52:37 - [INFO] - 68 filas, 5 columnas, 00:37.8 consultando, 00:00.3 descargando, 00:00.0 convirtiendo

 471/471 DATAFRAME                                            finalizado   09:51:58 AM     00:38.3
---------------------------------------------------------------------------------------------------