In [2]:
# Tecnología
import json
import calendar
import pandas as pd
from sparky_bc import Sparky
import datetime as dt
from dateutil.relativedelta import relativedelta

# files lz conection
path_sparky_conf = '/Users/santlond/Documents/sparky_conf.json'

# Configurar conexión a LZ
with open(path_sparky_conf, 'rb') as JSON_lz_File:
    sp_config = json.loads(JSON_lz_File.read())
    
USER='santlond'
PASS=sp_config['ID']
DSN='IMPALA_PROD'
LOGDIR= 'logs'
# sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp")
sparky = Sparky(username=USER, password=PASS, dsn=DSN, hostname="sbmdeblze004.bancolombia.corp", spark_submit="spark3-submit")
 
# sparky = Sparky(username=USER, password=PASS, dsn=DSN)

helper = sparky.helper

/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
2026-02-05 14:09:28 - [WARNING] - No se encontro la carpeta "/Users/santlond/Documents/ADQUIRENCIA_FERIA_EVA/logs" para guardar los logs

 ____  _____ __  __  ___ _____ _____
|  _ \| ____|  \/  |/ _ \_   _| ____|
| |_) |  _| | |\/| | | | || | |  _|
|  _ <| |___| |  | | |_| || | | |___
|_| \_\_____|_|  |_|\___/ |_| |_____|

 ____  ____   _    ____  _  __
/ ___||  _ \ / \  |  _ \| |/ /
\___ \| |_) / _ \ | |_) | ' /
 ___) |  __/ ___ \|  _ <| . \
|____/|_| /_/   \_\_| \_\_|\_\

# Introducción

Por dinámica de tiempo se quiere decir que un cliente se puede vincular, luego desvincularse y finalmente volverse a vincular

Se evidencia que los registros en la tabla `resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf` las vinculaciones de adquirencia no comparte registros con la tabla `resultados_wompi.wompi_merchants` que contiene las vinculaciones a wompi

In [32]:
# HASTA QUE AÑO MES SE HAN ACTUALIZADO LAS TRXS
periodo_actual_trxs = '202511'
periodo_actual_trxs

'202511'

# Evolución vinculación aceptación comercios [Adquirencia + Wompi]

## Adquirencia

In [33]:
dict_ult_ing_adqu_vinc = helper.obtener_ultima_ingestion('resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf')
dict_ult_ing_adqu_vinc

2026-01-16 16:42:22 - [INFO] - Buscando fechas para resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf
/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:476: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
2026-01-16 16:42:23 - [INFO] - Finalizo la busqueda, duracion: 00:00.4, resultado: {'year': 2026, 'month': 1, 'day': 7}

{'year': 2026, 'month': 1, 'day': 7}

In [34]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_hist_vinc_adqu PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_hist_vinc_adqu STORED AS PARQUET AS WITH vinculados AS
  (SELECT codigo_unico,
          extract(to_timestamp(concat(cast(YEAR AS string), '-', cast(MONTH AS string), '-01'), 'yyyy-M-dd') - INTERVAL 1 MONTH, 'year')*100 + extract(to_timestamp(concat(cast(YEAR AS string), '-', cast(MONTH AS string), '-01'), 'yyyy-M-dd') - INTERVAL 1 MONTH, 'month') AS fecha_ym
      FROM resultados_vspc_medios_de_pago.gsap_cun_conso_cu_vf
      WHERE YEAR <= """ + str(dict_ult_ing_adqu_vinc['year']) + """
      AND MONTH BETWEEN 1 AND 12
      AND DAY BETWEEN 1 AND 31),
                                                                                       conteo AS
  (SELECT fecha_ym,
          count(*) AS num_vinc_new,
          cast(left(cast(fecha_ym AS STRING), 4) AS int) AS YEAR,
          cast(right(cast(fecha_ym AS STRING), 2) AS int) AS mes
   FROM vinculados
   GROUP BY 1)
SELECT fecha_ym,
       num_vinc_new,
       sum(num_vinc_new) OVER (PARTITION BY YEAR
                           ORDER BY YEAR,
                                    mes ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_vinc_new_cumsum_ym,
                          'adquirencia' AS producto
FROM conteo
ORDER BY fecha_ym DESC;
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_hist_vinc_adqu;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 21/21      DROP ...o_aceptacion_comercios_hist_vinc_adqu   finalizado   04:42:23 PM     00:00.2
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 22/22    CREATE ...o_aceptacion_comercios_hist_vinc_adqu   finalizado   04:42:23 PM     00:01.1
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 23/23   COMPUTE ...o_aceptacion_comercios_hist_vinc_adqu   finalizado   04:42:24 PM     00:17.0
-------------------------------------------------------------------------------------------------

## Wompi

In [35]:
dict_ult_ing_wompi_merch = helper.obtener_ultima_ingestion('resultados_wompi.wompi_merchants')
dict_ult_ing_wompi_merch

2026-01-16 16:42:41 - [INFO] - Buscando fechas para resultados_wompi.wompi_merchants
/Users/santlond/Documents/venv_py39_odbc/lib/python3.9/site-packages/helper/helper.py:476: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, cn)
2026-01-16 16:42:42 - [INFO] - Finalizo la busqueda, duracion: 00:00.4, resultado: {'year': 2026, 'month': 1, 'day': 16}

{'year': 2026, 'month': 1, 'day': 16}

In [36]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_hist_vinc_wompi PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_hist_vinc_wompi STORED AS PARQUET AS
WITH conteo AS (
SELECT CASt(left(cast(creado as string), 6) as int) as fecha_ym, 
       count(*) as num_vinc_new
FROM resultados_wompi.wompi_merchants
WHERE YEAR = """ + str(dict_ult_ing_wompi_merch['year']) + """
  AND MONTH = """ + str(dict_ult_ing_wompi_merch['month']) + """
  AND DAY = """ + str(dict_ult_ing_wompi_merch['day']) + """
  AND modelo = 'Agregador'
  and activo = 'A'
  and desembolsos_permitidos = 'Si'
GROUP BY 1
), conteo_y_m AS (
SELECT fecha_ym,
        num_vinc_new,
        cast(left(cast(fecha_ym AS STRING), 4) AS int) AS YEAR,
        cast(right(cast(fecha_ym AS STRING), 2) AS int) AS mes
FROM conteo
)
SELECT fecha_ym,
       num_vinc_new,
       sum(num_vinc_new) OVER (PARTITION BY YEAR
                           ORDER BY YEAR,
                                    mes ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_vinc_new_cumsum_ym,
        'wompi' AS producto
FROM conteo_y_m
ORDER BY fecha_ym DESC;
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_hist_vinc_wompi;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 24/24      DROP ..._aceptacion_comercios_hist_vinc_wompi   finalizado   04:42:42 PM     00:00.1
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 25/25    CREATE ..._aceptacion_comercios_hist_vinc_wompi   finalizado   04:42:42 PM     00:01.4
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 26/26   COMPUTE ..._aceptacion_comercios_hist_vinc_wompi   finalizado   04:42:44 PM     00:00.6
-------------------------------------------------------------------------------------------------

# Vinculación aceptación comercios

In [37]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_vinc PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_vinc STORED AS PARQUET AS
WITH junte AS
  (SELECT fecha_ym,
          num_vinc_new,
          num_vinc_new_cumsum_ym,
          producto
   FROM proceso.mdo_aceptacion_comercios_hist_vinc_adqu
   UNION ALL SELECT fecha_ym,
                    num_vinc_new,
                    num_vinc_new_cumsum_ym,
                    producto
   FROM proceso.mdo_aceptacion_comercios_hist_vinc_wompi),
     agregado AS
  (SELECT fecha_ym,
          cast(left(cast(fecha_ym AS STRING), 4) AS int) AS YEAR,
          cast(right(cast(fecha_ym AS STRING), 2) AS int) AS mes,
          sum(num_vinc_new) AS num_vinc_new,
          1 AS secuencia2
   FROM junte
   GROUP BY 1,
            2,
            3)
SELECT fecha_ym,
       num_vinc_new,
       sum(num_vinc_new) OVER (PARTITION BY secuencia2 ORDER BY fecha_ym ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_vinc_cumsum,
       sum(num_vinc_new) OVER (PARTITION BY YEAR
                           ORDER BY YEAR,
                                    mes ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS num_vinc_new_cumsum_ym
FROM agregado
ORDER BY fecha_ym DESC;
"""
df_outcome = helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_vinc;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 27/27      DROP    proceso.mdo_aceptacion_comercios_vinc   finalizado   04:42:44 PM     00:00.2
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 28/28    CREATE    proceso.mdo_aceptacion_comercios_vinc   finalizado   04:42:45 PM     00:02.2
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 29/29   COMPUTE    proceso.mdo_aceptacion_comercios_vinc   finalizado   04:42:47 PM     00:01.6
-------------------------------------------------------------------------------------------------

In [38]:
sql = """
SELECT fecha_ym,
       num_vinc_new,
       num_vinc_cumsum,
       num_vinc_new_cumsum_ym
FROM proceso.mdo_aceptacion_comercios_vinc
ORDER BY fecha_ym DESC
"""
df_outcome = helper.obtener_dataframe(sql)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 30/30 DATAFRAME                                            ejecutando   04:42:48 PM

2026-01-16 16:42:49 - [INFO] - 88 filas, 4 columnas, 00:00.5 consultando, 00:00.1 descargando, 00:00.0 convirtiendo

 30/30 DATAFRAME                                            finalizado   04:42:48 PM     00:00.7
-------------------------------------------------------------------------------------------------

In [39]:
df_outcome[40:].head(20)

    fecha_ym  num_vinc_new  num_vinc_cumsum  num_vinc_new_cumsum_ym
40    202209          5797           178187                   49591
41    202208          6820           172390                   43794
42    202207          7554           165570                   36974
43    202206          6363           158016                   29420
44    202205          7256           151653                   23057
45    202204          2745           144397                   15801
46    202203          3712           141652                   13056
47    202202          4970           137940                    9344
48    202201          4374           132970                    4374
49    202112          5570           128596                  115843
50    202111          9861           123026                  110273
51    202110          9103           113165                  100412
52    202109          1289           104062                   91309
53    202108          8809           102773                   90020
54    202107          8322            93964                   81211
55    202106          3633            85642                   72889
56    202105          5379            82009                   69256
57    202104          7240            76630                   63877
58    202103          6639            69390                   56637
59    202102          5288            62751                   49998

# Uso de vinculados nuevos aceptación comercios

In [40]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_num_vinc_new_uso PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_num_vinc_new_uso STORED AS PARQUET AS
WITH uso_adqui AS
  (SELECT periodo,
          count(*) AS num_vinc_new_uso_adqu
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist_con_dup
   WHERE producto = 'adqui'
   AND tipo_cliente = 'nuevos'
   GROUP BY 1),
     uso_wompi AS
  (SELECT periodo,
          count(*) AS num_vinc_new_uso_womp
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist_con_dup
   WHERE producto = 'wompi'
   AND tipo_cliente = 'nuevos'
   GROUP BY 1)
SELECT a.periodo as fecha_ym,
       a.num_vinc_new_uso_adqu + nvl(b.num_vinc_new_uso_womp, 0) AS num_vinc_new_uso_cumsum_ym
FROM uso_adqui AS a
LEFT JOIN uso_wompi AS b ON a.periodo = b.periodo
ORDER BY a.periodo DESC;
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_num_vinc_new_uso;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 31/31      DROP ...aceptacion_comercios_num_vinc_new_uso   finalizado   04:42:49 PM     00:00.1
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 32/32    CREATE ...aceptacion_comercios_num_vinc_new_uso   finalizado   04:42:50 PM     00:14.1
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 33/33   COMPUTE ...aceptacion_comercios_num_vinc_new_uso   finalizado   04:43:04 PM     00:01.6
-------------------------------------------------------------------------------------------------

# Uso de vinculados viejos aceptación comercios

In [41]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_num_vinc_old_uso PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_num_vinc_old_uso STORED AS PARQUET AS
WITH uso_adqui AS
  (SELECT periodo,
          count(*) AS num_vinc_old_uso_adqu
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist_con_dup
   WHERE producto = 'adqui'
   AND tipo_cliente = 'viejos'
   GROUP BY 1),
     uso_wompi AS
  (SELECT periodo,
          count(*) AS num_vinc_old_uso_womp
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist_con_dup
   WHERE producto = 'wompi'
   AND tipo_cliente = 'viejos'
   GROUP BY 1)
SELECT a.periodo as fecha_ym,
       a.num_vinc_old_uso_adqu + nvl(b.num_vinc_old_uso_womp, 0) AS num_vinc_old_uso_cumsum_ym
FROM uso_adqui AS a
LEFT JOIN uso_wompi AS b ON a.periodo = b.periodo
ORDER BY a.periodo DESC;
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_num_vinc_old_uso;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 34/34      DROP ...aceptacion_comercios_num_vinc_old_uso   finalizado   04:43:06 PM     00:00.2
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 35/35    CREATE ...aceptacion_comercios_num_vinc_old_uso   finalizado   04:43:06 PM     00:10.7
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 36/36   COMPUTE ...aceptacion_comercios_num_vinc_old_uso   finalizado   04:43:17 PM     00:02.6
-------------------------------------------------------------------------------------------------

# Uso de vinculados todos aceptación comercios

In [42]:
sql_drop = """DROP TABLE IF EXISTS proceso.mdo_aceptacion_comercios_num_vinc_all_uso PURGE;"""
helper.ejecutar_consulta(sql_drop)

sql = """
CREATE TABLE proceso.mdo_aceptacion_comercios_num_vinc_all_uso STORED AS PARQUET AS
WITH uso_adqui AS
  (SELECT periodo,
          count(*) AS num_vinc_all_uso_adqu
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist_con_dup
   WHERE producto = 'adqui'
   AND tipo_cliente = 'todos'
   GROUP BY 1),
     uso_wompi AS
  (SELECT periodo,
          count(*) AS num_vinc_all_uso_womp
   FROM proceso_vdm.mdo_adquirencia_y_wompi_vinculaciones_con_trxs_hist_con_dup
   WHERE producto = 'wompi'
   AND tipo_cliente = 'todos'
   GROUP BY 1)
SELECT a.periodo as fecha_ym,
       a.num_vinc_all_uso_adqu + nvl(b.num_vinc_all_uso_womp, 0) AS num_vinc_all_uso_cumsum_ym
FROM uso_adqui AS a
LEFT JOIN uso_wompi AS b ON a.periodo = b.periodo
ORDER BY a.periodo DESC;
"""
helper.ejecutar_consulta(sql)

sql_compute = """COMPUTE INCREMENTAL STATS proceso.mdo_aceptacion_comercios_num_vinc_all_uso;"""
helper.ejecutar_consulta(sql_compute)

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 37/37      DROP ...aceptacion_comercios_num_vinc_all_uso   finalizado   04:43:19 PM     00:00.2
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 38/38    CREATE ...aceptacion_comercios_num_vinc_all_uso   finalizado   04:43:20 PM     00:12.9
-------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 39/39   COMPUTE ...aceptacion_comercios_num_vinc_all_uso   finalizado   04:43:33 PM     00:01.4
-------------------------------------------------------------------------------------------------

# Tabla resultado

In [43]:
sql = """
WITH outcome1 AS
  (SELECT a.fecha_ym,
          a.num_vinc_new,
          a.num_vinc_cumsum,
          a.num_vinc_new_cumsum_ym,
          nvl(b.num_vinc_new_uso_cumsum_ym, 0) AS num_vinc_new_uso_cumsum_ym,
          round(nvl(b.num_vinc_new_uso_cumsum_ym, 0)/a.num_vinc_new_cumsum_ym, 4) AS num_vinc_new_prop_uso,
          nvl(c.num_vinc_old_uso_cumsum_ym, 0) AS num_vinc_old_uso_cumsum_ym,
          nvl(d.num_vinc_all_uso_cumsum_ym, 0) AS num_vinc_all_uso_cumsum_ym,
          round(nvl(d.num_vinc_all_uso_cumsum_ym, 0)/a.num_vinc_cumsum, 4) AS num_vinc_all_prop_uso,
          left(cast(a.fecha_ym AS string), 4) AS YEAR,
          right(cast(a.fecha_ym AS string), 2) AS mes
   FROM proceso.mdo_aceptacion_comercios_vinc AS a
   LEFT JOIN proceso.mdo_aceptacion_comercios_num_vinc_new_uso AS b ON a.fecha_ym = b.fecha_ym
   LEFT JOIN proceso.mdo_aceptacion_comercios_num_vinc_old_uso AS c ON a.fecha_ym = c.fecha_ym
   LEFT JOIN proceso.mdo_aceptacion_comercios_num_vinc_all_uso AS d ON a.fecha_ym = d.fecha_ym),
     outcome2 AS
  (SELECT fecha_ym,
          num_vinc_cumsum AS num_vinc_old,
          cast(cast(YEAR AS int) + 1 AS string) AS YEAR
   FROM outcome1
   WHERE mes = '12')
SELECT a.fecha_ym,
       CONCAT(a.YEAR, '/', a.mes, '/', '01') AS fecha_ym2,
       a.num_vinc_new,
       a.num_vinc_new_cumsum_ym,
       a.num_vinc_new_uso_cumsum_ym,
       a.num_vinc_new_prop_uso,
       b.num_vinc_old,
       a.num_vinc_old_uso_cumsum_ym,
       round(a.num_vinc_old_uso_cumsum_ym/b.num_vinc_old, 4) AS num_vinc_old_prop_uso,
       a.num_vinc_cumsum,
       a.num_vinc_all_uso_cumsum_ym,
       a.num_vinc_all_prop_uso
FROM outcome1 AS a
LEFT JOIN outcome2 AS b ON a.year = b.year
WHERE a.fecha_ym BETWEEN 202201 AND 202511
ORDER BY a.fecha_ym DESC;
"""
# print(sql)
df_outcome = helper.obtener_dataframe(sql)
df_outcome

-------------------------------------------------------------------------------------------------
   i     tipo                     nombre                     estado     hora_inicio   duracion
-------------------------------------------------------------------------------------------------
 40/40 DATAFRAME                                            finalizado   04:43:34 PM     00:01.1
-------------------------------------------------------------------------------------------------

2026-01-16 16:43:35 - [INFO] - 47 filas, 12 columnas, 00:00.9 consultando, 00:00.1 descargando, 00:00.0 convirtiendo

,fecha_ym,fecha_ym2,num_vinc_new,num_vinc_new_cumsum_ym,num_vinc_new_uso_cumsum_ym,num_vinc_new_prop_uso,num_vinc_old,num_vinc_old_uso_cumsum_ym,num_vinc_old_prop_uso,num_vinc_cumsum,num_vinc_all_uso_cumsum_ym,num_vinc_all_prop_uso
0,202511,2025/11/01,15051,100796,38823,0.3852,323753,103274,0.3190,424549,142097,0.3347
1,202510,2025/10/01,16248,85745,34180,0.3986,323753,102731,0.3173,409498,136911,0.3343
2,202509,2025/09/01,22796,69497,29340,0.4222,323753,102090,0.3153,393250,131430,0.3342
3,202508,2025/08/01,7078,46701,22020,0.4715,323753,101310,0.3129,370454,123330,0.3329
4,202507,2025/07/01,8146,39623,19882,0.5018,323753,100437,0.3102,363376,120319,0.3311
5,202506,2025/06/01,6345,31477,15970,0.5074,323753,99408,0.3070,355230,115378,0.3248
6,202505,2025/05/01,6469,25132,12905,0.5135,323753,98241,0.3034,348885,111146,0.3186
7,202504,2025/04/01,5234,18663,9492,0.5086,323753,96434,0.2979,342416,105926,0.3093
8,202503,2025/03/01,4855,13429,6541,0.4871,323753,94424,0.2917,337182,100965,0.2994
9,202502,2025/02/01,4466,8574,3989,0.4652,323753,91308,0.2820,332327,95297,0.2868
10,202501,2025/01/01,4108,4108,1619,0.3941,323753,85796,0.2650,327861,87415,0.2666
11,202412,2024/12/01,5004,65265,39667,0.6078,258488,100526,0.3889,323753,140193,0.4330
12,202411,2024/11/01,5389,60261,35808,0.5942,258488,100092,0.3872,318749,135900,0.4264
13,202410,2024/10/01,5860,54872,32221,0.5872,258488,99571,0.3852,313360,131792,0.4206
14,202409,2024/09/01,6490,49012,28756,0.5867,258488,98985,0.3829,307500,127741,0.4154
15,202408,2024/08/01,5472,42522,24609,0.5787,258488,98359,0.3805,301010,122968,0.4085
16,202407,2024/07/01,6441,37050,21322,0.5755,258488,97578,0.3775,295538,118900,0.4023
17,202406,2024/06/01,3548,30609,17642,0.5764,258488,96580,0.3736,289097,114222,0.3951
18,202405,2024/05/01,5245,27061,14993,0.5540,258488,95515,0.3695,285549,110508,0.3870
19,202404,2024/04/01,5247,21816,11875,0.5443,258488,93968,0.3635,280304,105843,0.3776
20,202403,2024/03/01,7052,16569,8816,0.5321,258488,91919,0.3556,275057,100735,0.3662
21,202402,2024/02/01,6052,9517,5213,0.5478,258488,89032,0.3444,268005,94245,0.3517
22,202401,2024/01/01,3465,3465,1531,0.4418,258488,83314,0.3223,261953,84845,0.3239
23,202312,2023/12/01,4203,65298,47052,0.7206,193190,88413,0.4576,258488,135465,0.5241
24,202311,2023/11/01,7062,61095,42543,0.6963,193190,88034,0.4557,254285,130577,0.5135
25,202310,2023/10/01,5778,54033,37858,0.7006,193190,87603,0.4535,247223,125461,0.5075
26,202309,2023/09/01,5318,48255,33878,0.7021,193190,87123,0.4510,241445,121001,0.5012
27,202308,2023/08/01,12856,42937,29498,0.6870,193190,86565,0.4481,236127,116063,0.4915
28,202307,2023/07/01,951,30081,21785,0.7242,193190,85840,0.4443,223271,107625,0.4820
29,202306,2023/06/01,4961,29130,20748,0.7123,193190,84976,0.4399,222320,105724,0.4755
30,202305,2023/05/01,5770,24169,16469,0.6814,193190,83936,0.4345,217359,100405,0.4619
31,202304,2023/04/01,4713,18399,12444,0.6763,193190,82677,0.4280,211589,95121,0.4496
32,202303,2023/03/01,5670,13686,8955,0.6543,193190,80976,0.4192,206876,89931,0.4347
33,202302,2023/02/01,2648,8016,4882,0.6090,193190,78265,0.4051,201206,83147,0.4132
34,202301,2023/01/01,5368,5368,1564,0.2914,193190,73590,0.3809,198558,75154,0.3785
35,202212,2022/12/01,3467,64594,0,0.0000,128596,0,0.0000,193190,0,0.0000
36,202211,2022/11/01,5824,61127,0,0.0000,128596,0,0.0000,189723,0,0.0000
37,202210,2022/10/01,5712,55303,0,0.0000,128596,0,0.0000,183899,0,0.0000
38,202209,2022/09/01,5797,49591,0,0.0000,128596,0,0.0000,178187,0,0.0000
39,202208,2022/08/01,6820,43794,0,0.0000,128596,0,0.0000,172390,0,0.0000
40,202207,2022/07/01,7554,36974,0,0.0000,128596,0,0.0000,165570,0,0.0000
41,202206,2022/06/01,6363,29420,0,0.0000,128596,0,0.0000,158016,0,0.0000
42,202205,2022/05/01,7256,23057,0,0.0000,128596,0,0.0000,151653,0,0.0000
43,202204,2022/04/01,2745,15801,0,0.0000,128596,0,0.0000,144397,0,0.0000
44,202203,2022/03/01,3712,13056,0,0.0000,128596,0,0.0000,141652,0,0.0000
45,202202,2022/02/01,4970,9344,0,0.0000,128596,0,0.0000,137940,0,0.0000
46,202201,2022/01/01,4374,4374,0,0.0000,128596,0,0.0000,132970,0,0.0000

In [44]:
df_outcome.to_excel('main_data/evolucion_vinculacion_y_uso_adquirencia_y_wompi_con_duplicados.xlsx')

# Eliminación tablas proceso.

In [3]:
# Eliminación tablas proceso.
tablas_borrar = ['proceso.mdo_aceptacion_comercios_hist_vinc_adqu', 'proceso.mdo_aceptacion_comercios_hist_vinc_wompi', 'proceso.mdo_aceptacion_comercios_vinc', 'proceso.mdo_aceptacion_comercios_num_vinc_new_uso', 'proceso.mdo_aceptacion_comercios_num_vinc_old_uso', 'proceso.mdo_aceptacion_comercios_num_vinc_all_uso']

for tabla in tablas_borrar:
    sql_drop = f"""DROP TABLE IF EXISTS {tabla} PURGE;"""
    helper.ejecutar_consulta(sql_drop)

2026-02-05 14:09:34 - [INFO] - Transcurrido: 1770318574, Tiempo de Refresco = 1000

------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 1/1 DROP ...o_aceptacion_comercios_hist_vinc_adqu   finalizado   02:09:35 PM     00:00.7
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 2/2 DROP ..._aceptacion_comercios_hist_vinc_wompi   finalizado   02:09:35 PM     00:00.1
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 3/3 DROP    proceso.mdo_aceptacion_comercios_vinc   finalizado   02:09:36 PM     00:00.0
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 4/4 DROP ...aceptacion_comercios_num_vinc_new_uso   finalizado   02:09:36 PM     00:00.0
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 5/5 DROP ...aceptacion_comercios_num_vinc_old_uso   finalizado   02:09:36 PM     00:00.0
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
  i  tipo                  nombre                     estado     hora_inicio   duracion
------------------------------------------------------------------------------------------
 6/6 DROP ...aceptacion_comercios_num_vinc_all_uso   finalizado   02:09:36 PM     00:00.0
------------------------------------------------------------------------------------------